services:
  loki:
    image: grafana/loki
    container_name: smartjam-loki
    ports:
      - "3100:3100"
    volumes:
      - ./infra/loki/local-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml


  grafana:
    image: grafana/grafana
    container_name: smartjam-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./infra/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana

  tempo:
    image: grafana/tempo:2.10.0
    container_name: smartjam-tempo
    ports:
      - "3200:3200"
    volumes:
      - ./infra/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    command: -config.file=/etc/tempo.yaml

  prometheus:
    image: prom/prometheus
    container_name: smartjam-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver

  alloy:
    image: grafana/alloy
    container_name: smartjam-alloy
    ports:
      - "4317:4317"
      - "4318:4318"
      - "12345:12345"
    volumes:
      - ./infra/alloy/config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy


volumes:
  loki_data:
  tempo_data:
  prometheus_data:
  grafana_data: